#
###################################
# Site wide configuration
####################################
#
title: marcd.dev
email: 
description: marcd.dev site powered by jekyll.
url: https://marcd.dev  # the base hostname & protocol for your site
keywords: ["software","developer","programming","devops","cloud native","java","spring cloud","messaging","blog","jekyll"]
# Repo that will contain issue comments for blog posts
github_comments_repository: Mrc0113/mrc0113.github.io
#
###################################
# Jekyll configuration
####################################
#
timezone:          America/New_York
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Marc DiPasquale
  avatar: avatar.jpg
  job: "Developer Advocate @ Solace."
  bio: "Software Engineer. UCF CS Alumnus. My apps are usually event-driven and hanging out in the clouds"
  email:
  disqus-shortname:
  twitter: Mrc0113 #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-139902608-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Mrc0113 #username
  gitlab: #username
  stackoverflow: 1304010/mrc0113 #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: marc-dipasquale #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
